import Head from "next/head"
import { Button } from "@chakra-ui/react"
import { MetaMaskConnector } from "@wagmi/core/connectors/metaMask"
import { useConnect } from "wagmi"

export default function Home() {
  const { connect } = useConnect({ connector: new MetaMaskConnector() })

  return (
    <>
      <Head>
        <title>Terrabio DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={() => connect()}>Connect</Button>
    </>
  )
}
